//! Cross-verification tests for Zolt compatibility
//!
//! This module provides tests to verify that proofs generated by Zolt
//! can be verified by Jolt's verifier.
//!
//! ## Usage
//!
//! 1. Generate reference preprocessing in Jolt:
//!    ```bash
//!    cargo run --example fibonacci -- --save
//!    # This creates /tmp/jolt_verifier_preprocessing.dat
//!    ```
//!
//! 2. Generate proof in Zolt using the same program:
//!    ```bash
//!    cd /path/to/zolt
//!    zig build -Doptimize=ReleaseFast
//!    ./zig-out/bin/zolt prove fibonacci.elf --jolt-format -o /tmp/zolt_proof.bin
//!    ```
//!
//! 3. Run cross-verification test:
//!    ```bash
//!    cargo test zolt_compat
//!    ```

#[cfg(test)]
mod tests {
    use crate::zkvm::Serializable;
    use std::fs;
    use std::path::Path;

    /// Test that we can deserialize a Zolt-generated proof
    ///
    /// This test demonstrates the basic deserialization capability.
    /// It requires a Zolt proof file at /tmp/zolt_proof.bin
    #[test]
    #[ignore = "requires Zolt proof file - run manually"]
    fn test_deserialize_zolt_proof() {
        use crate::zkvm::RV64IMACProof;

        let proof_path = "/tmp/zolt_proof.bin";
        if !Path::new(proof_path).exists() {
            println!("Skipping test: Zolt proof not found at {}", proof_path);
            println!("Generate with: ./zolt prove program.elf --jolt-format -o {}", proof_path);
            return;
        }

        let proof_bytes = fs::read(proof_path).expect("Failed to read Zolt proof");
        println!("Read {} bytes from Zolt proof", proof_bytes.len());

        // Try to deserialize
        match RV64IMACProof::deserialize_from_bytes(&proof_bytes) {
            Ok(proof) => {
                println!("Successfully deserialized Zolt proof!");
                println!("  Trace length: {}", proof.trace_length);
                println!("  RAM K: {}", proof.ram_K);
                println!("  Bytecode K: {}", proof.bytecode_K);
                println!("  Commitments: {}", proof.commitments.len());
            }
            Err(e) => {
                panic!("Failed to deserialize Zolt proof: {:?}", e);
            }
        }
    }

    /// Test full cross-verification with Zolt proof
    ///
    /// Requires:
    /// - /tmp/jolt_verifier_preprocessing.dat (from Jolt)
    /// - /tmp/zolt_proof.bin (from Zolt)
    /// - /tmp/fib_io_device.bin (from Jolt)
    #[test]
    #[ignore = "requires full Zolt proof setup - run manually"]
    fn test_verify_zolt_proof() {
        use crate::zkvm::{RV64IMACProof, RV64IMACVerifier};
        use common::jolt_device::JoltDevice;

        // Check required files exist
        let preprocessing_path = "/tmp/jolt_verifier_preprocessing.dat";
        let proof_path = "/tmp/zolt_proof.bin";
        let io_path = "/tmp/fib_io_device.bin";

        for path in [preprocessing_path, proof_path, io_path] {
            if !Path::new(path).exists() {
                println!("Missing required file: {}", path);
                println!("\nTo generate Jolt files:");
                println!("  cargo run --example fibonacci -- --save");
                println!("\nTo generate Zolt proof:");
                println!("  ./zolt prove fibonacci.elf --jolt-format -o {}", proof_path);
                return;
            }
        }

        // Load verifier preprocessing
        let preprocessing_bytes = fs::read(preprocessing_path)
            .expect("Failed to read verifier preprocessing");
        let preprocessing = crate::zkvm::verifier::JoltVerifierPreprocessing::deserialize_from_bytes(
            &preprocessing_bytes,
        )
        .expect("Failed to deserialize preprocessing");

        // Load Zolt proof
        let proof_bytes = fs::read(proof_path).expect("Failed to read Zolt proof");
        let proof = RV64IMACProof::deserialize_from_bytes(&proof_bytes)
            .expect("Failed to deserialize proof");

        // Load program I/O
        let io_bytes = fs::read(io_path).expect("Failed to read program I/O");
        let program_io = JoltDevice::deserialize_from_bytes(&io_bytes)
            .expect("Failed to deserialize program I/O");

        println!("Loaded all files, attempting verification...");
        println!("  Proof trace length: {}", proof.trace_length);
        println!("  Proof commitments: {}", proof.commitments.len());

        // Create verifier
        match RV64IMACVerifier::new(
            &preprocessing,
            proof,
            program_io,
            None, // no trusted advice
            None, // no debug info
        ) {
            Ok(verifier) => {
                println!("Verifier created successfully, running verification...");
                match verifier.verify() {
                    Ok(()) => {
                        println!("SUCCESS: Zolt proof verified by Jolt!");
                    }
                    Err(e) => {
                        panic!("Verification failed: {:?}", e);
                    }
                }
            }
            Err(e) => {
                panic!("Failed to create verifier: {:?}", e);
            }
        }
    }

    /// Minimal test to verify byte format compatibility
    ///
    /// This generates a proof in Jolt, serializes it, and verifies
    /// we can deserialize it back - establishing the baseline format.
    #[test]
    fn test_jolt_proof_roundtrip() {
        // This test uses internal Jolt functions to verify
        // our understanding of the serialization format is correct
        use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};

        // Test basic field element serialization
        use ark_bn254::Fr;
        use ark_ff::One;

        let fe = Fr::one();
        let mut bytes = Vec::new();
        fe.serialize_compressed(&mut bytes).expect("serialize");
        assert_eq!(bytes.len(), 32, "Fr should serialize to 32 bytes");

        let fe2 = Fr::deserialize_compressed(&bytes[..]).expect("deserialize");
        assert_eq!(fe, fe2, "Roundtrip should preserve value");

        println!("Basic field element roundtrip: OK");
    }
}
